var searchData=
[
  ['_5f_5fhalf_5fraw_0',['__half_raw',['../struct_eigen_1_1half__impl_1_1____half__raw.html',1,'Eigen::half_impl']]],
  ['_5fcl_5fbuffer_5fregion_1',['_cl_buffer_region',['../struct__cl__buffer__region.html',1,'']]],
  ['_5fcl_5fimage_5fdesc_2',['_cl_image_desc',['../struct__cl__image__desc.html',1,'']]],
  ['_5fcl_5fimage_5fformat_3',['_cl_image_format',['../struct__cl__image__format.html',1,'']]],
  ['_5fcl_5fmotion_5festimation_5fdesc_5fintel_4',['_cl_motion_estimation_desc_intel',['../struct__cl__motion__estimation__desc__intel.html',1,'']]],
  ['_5fjavavm_5',['_JavaVM',['../struct___java_v_m.html',1,'']]],
  ['_5fjnienv_6',['_JNIEnv',['../struct___j_n_i_env.html',1,'']]],
  ['_5fpb_5fbit128_7',['_PB_Bit128',['../class_phone_bit_1_1___p_b___bit128.html',1,'PhoneBit']]],
  ['_5fpb_5fbit16_8',['_PB_Bit16',['../class_phone_bit_1_1___p_b___bit16.html',1,'PhoneBit']]],
  ['_5fpb_5fbit32_9',['_PB_Bit32',['../class_phone_bit_1_1___p_b___bit32.html',1,'PhoneBit']]],
  ['_5fpb_5fbit4_10',['_PB_Bit4',['../class_phone_bit_1_1___p_b___bit4.html',1,'PhoneBit']]],
  ['_5fpb_5fbit64_11',['_PB_Bit64',['../class_phone_bit_1_1___p_b___bit64.html',1,'PhoneBit']]],
  ['_5fpb_5fbit8_12',['_PB_Bit8',['../class_phone_bit_1_1___p_b___bit8.html',1,'PhoneBit']]],
  ['_5fpb_5ffloat16_13',['_PB_Float16',['../class_phone_bit_1_1___p_b___float16.html',1,'PhoneBit']]],
  ['_5fpb_5ffloat32_14',['_PB_Float32',['../class_phone_bit_1_1___p_b___float32.html',1,'PhoneBit']]],
  ['_5fpb_5fint16_15',['_PB_Int16',['../class_phone_bit_1_1___p_b___int16.html',1,'PhoneBit']]],
  ['_5fpb_5fint32_16',['_PB_Int32',['../class_phone_bit_1_1___p_b___int32.html',1,'PhoneBit']]],
  ['_5fpb_5fint8_17',['_PB_Int8',['../class_phone_bit_1_1___p_b___int8.html',1,'PhoneBit']]],
  ['_5fpb_5fuint16_18',['_PB_UInt16',['../class_phone_bit_1_1___p_b___u_int16.html',1,'PhoneBit']]],
  ['_5fpb_5fuint32_19',['_PB_UInt32',['../class_phone_bit_1_1___p_b___u_int32.html',1,'PhoneBit']]],
  ['_5fpb_5fuint8_20',['_PB_UInt8',['../class_phone_bit_1_1___p_b___u_int8.html',1,'PhoneBit']]]
];
